### ISSUE TITLE
Undefined method `store_previous_model_for_avatar`

### ISSUE THREAD

**Issue by 23tux** [carrierwaveuploader/carrierwave-mongoid#142]
Hi,

I'm getting the error above, when I try to update a model that uses `mount_uploader`. I searched the repo and found this line

```
# mongoid.rb#32
before_update :"store_previous_model_for_#{column}"
```

When I create a model, everything works fine. But when I try to update the model, the callback tries to fire, but somehow it doesn't find the method `store_previous_model_for_avatar`.

Is this a method I have to implement by myself? Because I can't find any place, where such a method is defined. Or is this a bug? I tried the 0.7.1 version and also the master branch, same results.

**Comment by 23tux** [comment]
I think I found the issue: When you look at this commit https://github.com/carrierwaveuploader/carrierwave/commit/d42bc52dc91d074c5b658daf90880daa4ed257d7#diff-a55bff814d737fb514d27c33d9dbb64eL32 from the https://github.com/carrierwaveuploader/carrierwave repository, you can see, that they also removed the `before_update :"store_previous_model_for_#{column}"` callback, because they removed the whole method here: https://github.com/carrierwaveuploader/carrierwave/commit/d42bc52dc91d074c5b658daf90880daa4ed257d7#diff-419d854eb29fe4202e9613c5430b66fdL230

I'm not sure why they removed it, but I think carrierwave-mongoid has to updated ;)

**Comment by rmm5t** [comment]
> I'm not sure why they removed it, but I think carrierwave-mongoid has to updated ;)

I'm not sure yet either, but carrierwave also hasn't had an official release since this change.  carrierwave-mongoid already specifies that you must use carrierwave v0.10.0.

**Comment by 23tux** [comment]
Ok, but I need some stuff from the carrierwave master branch, so for now, I just define an empty `store_previous_model_for_avatar` method in my model, till it is fixed.

**Comment by rmm5t** [comment]
@23tux Since core carrierwave has outright removed this method, that's probably a safe approach to take, but I would also first want to investigate and make sure the behavior wasn't replaced by something else that carrierwave-mongoid needs to implement.

**Comment by adbeelitamar** [comment]
Any updates on this issue?

**Comment by rmm5t** [comment]
@adbeelitamar Sorry. No updates on this issue. I'm really swamped with other work and haven't been deep in carrierwave land for a little while. PRs welcome, but remember, there still isn't an official carrierwave version based on these changes to the API yet.

**Comment by maxkaplan** [comment]
@23tux @rmm5t - I also ran into this problem. I wrote a blank method and it fixed the error but now the previous file is NOT being replaced/deleted if there is a new file uploaded. Is this intended? One work around I thought of would just be to rename the filename so it would always overwrite it on edit?

**Comment by maxkaplan** [comment]
Hey guys - so since having the method blank does not delete the old file I hacked this together to get it working again... Keep in mind my mount is on 'file' (not avatar)

```
    def store_previous_model_for_file
        if file.remove_previously_stored_files_after_update && file_changed?
            @previous_model_for_file ||= self.find_previous_model_for_file       
        end
    end

    def find_previous_model_for_file       
        self.class.find(to_key.first)        
    end        

    def remove_previously_stored_file    
        if @previous_model_for_file && @previous_model_for_file.file.path != file.path && !file.path.nil?       
            @previous_model_for_file.file.remove!        
            @previous_model_for_file = nil        
        end      
    end
```

**Comment by ericraio** [comment]
Do we have a fix for this that can be merged and updated?

**Comment by jeremyhaile** [comment]
Can we please merge in one of the fixes above?

**Comment by rmm5t** [comment]
> Can we please merge in one of the fixes above?

Would really appreciate a green PR for this.

**Comment by rmm5t** [comment]
Closing stale issues. Hoping this will be resolved in our upcoming (next day or so) support for carrierwave 1.x, but please chime in here again if not.
